version: '3.3'

services:
  foodgram_db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
    container_name: foodgram_db

  foodgram_web:
    depends_on:
      - foodgram_db
    image: thxphila/foodgram-backend:latest
    expose:
      - 80
    restart: always
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/media/
    env_file:
      - ./.env
    container_name: foodgram_web
  
  frontend:
    depends_on:
      - foodgram_web
    image: thxphila/foodgram-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    

volumes:
  postgres_data:
  static_value:
  media_value:
